# Root directory - uncomment the appropriate line for your environment
rootdir: "/Users/mattg0/Docs/HorseBetAITensor/"
#rootdir: "/HorseBetAITensor"

# Active database configuration
active_db: "2years"  # Can be "full", "2years", or "5years"

# Path configurations
paths:
  data: "data"
  models: "model"
  logs: "logs"
  cache: "cache"

# Database configurations
databases:
  - name: "full"
    path: "data/hippique.db"
    description: "Full historical database"
  - name: "2years"
    path: "data/hippique2.db"
    description: "Last 2 years of data"
  - name: "5years"
    path: "data/hippique5.db"
    description: "Last 5 years of data"
  - name: "mysql"
    host: "localhost"
    user: "turfai"
    password: "welcome123"
    database: "pturf2024"

# Cache configurations
cache:
  historical_data:
    full: "cache/full_historical_data.parquet"
    2years: "cache/2years_historical_data.parquet"
    5years: "cache/5years_historical_data.parquet"
  training_data:
    full: "cache/full_training_data.parquet"
    2years: "cache/2years_training_data.parquet"
    5years: "cache/5years_training_data.parquet"

# Bet type configurations
bet_type:
  - name: "tierce"
    value: 3
  - name: "quarte"
    value: 4
  - name: "quinte"
    value: 5
  - name: "full"
    value: None

# Model configurations
model:
  - name: "lstm"
    base_path: "model/LSTM"
    train_script: "lstm_train_model.py"
    predict_script: "lstm_predict_race.py"
    model_paths:
      full: "full"
      2years: "2years"
      5years: "5years"
    artifacts:
      label_encoder: "lstm_label_encoder.pkl"
      label_encoder_idche: "lstm_label_encoder_idche.pkl"
      label_encoder_idJockey: "lstm_label_encoder_idJockey.pkl"
      model: "lstm_race_model.keras"
      scaler: "lstm_scaler.pkl"
    logs: "logs/lstm"

  - name: "forest"
    base_path: "model/Forest"
    train_script: "forest_train_model.py"
    predict_script: "forest_predict_race.py"
    model_paths:
      full: "full"
      2years: "2years"
      5years: "5years"
    artifacts:
      label_encoder: "label_encoder.pkl"
      label_encoder_idche: "label_encoder_idche.pkl"
      label_encoder_idJockey: "label_encoder_idJockey.pkl"
      model: "race_model.keras"
      scaler: "scaler.pkl"
    logs: "logs/forest"

  - name: "claude"
    base_path: "model/Claude"
    train_script: "claude_train_model.py"
    predict_script: "claude_predict_race.py"
    model_paths:
      full: "full"
      2years: "2years"
      5years: "5years"
    artifacts:
      rf_model: "rf_model.joblib"
      lstm_model: "lstm_model.keras"
      feature_engineer: "feature_engineering.joblib"
    logs: "logs/claude"

  - name: "hybrid"
    base_path: "model/Claude"
    train_script: "claude_train_model.py"
    predict_script: "claude_predict_race.py"
    model_paths:
      full: "full"
      2years: "2years"
      5years: "5years"
    artifacts:
      rf_model: "rf_model.joblib"
      lstm_model: "lstm_model.keras"
      feature_engineer: "feature_engineering.joblib"
    logs: "logs/hybrid"

telegram:
  bot_token: '7638183617:AAHS8UaVJUtZkESC5C5TaTQQyEVlthBANls'
  chat_id: '1051257832'

aspiturf:
  api_key: '8cdfGeF4pHeSOPv05dPnVyGaghL2'

test_comp_id: 1569175